### ISSUE TITLE
[BUG] android.view.InflateException: Binary XML file line #14: Binary XML file line #14: Error inflating class codes.side.andcolorpicker.hsl.HSLColorPickerSeekBar

### ISSUE THREAD

**Issue by JKorsten** [side-codes/andColorPicker#177]
**Describe the bug**
When I want to add the view to my main activity.xml I get an inflate error.

**To Reproduce**
1. Add `implementation "codes.side:andcolorpicker:0.5.0"` to app/build.gradle
2. Add: `<codes.side.andcolorpicker.hsl.HSLColorPickerSeekBar
        android:layout_width="200dp"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        android:layout_height="wrap_content"
        app:hslMode="hue" />` to main_activity.xml
3. Run the project

**Expected behavior**
It should run and the slider should be visible

**Extra information**
`Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable.mutate()' on a null object reference
        at codes.side.andcolorpicker.view.picker.ColorSeekBar.setupBackground(ColorSeekBar.kt:121)
        at codes.side.andcolorpicker.view.picker.ColorSeekBar.<init>(ColorSeekBar.kt:106)
2021-04-06 12:16:53.779 24098-24098/com.prowise.service.pronote_2021 E/AndroidRuntime:     at codes.side.andcolorpicker.view.picker.GradientColorSeekBar.<init>(GradientColorSeekBar.kt:16)
        at codes.side.andcolorpicker.hsl.HSLColorPickerSeekBar.<init>(HSLColorPickerSeekBar.kt:27)
        at codes.side.andcolorpicker.hsl.HSLColorPickerSeekBar.<init>(HSLColorPickerSeekBar.kt:25)
        at codes.side.andcolorpicker.hsl.HSLColorPickerSeekBar.<init>(Unknown Source:6)
        	... 30 more`

**Comment by dummyco** [comment]
@JKorsten, thank you for the report.
What version of Android are you running on?

**Comment by dummyco** [comment]
#184 should fix that.
Feel free to reopen if the issue persists!
